# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b5e8b9ba74a03edfd9c5579a06c7a9d950a7d623478cb2a5ebda9b9c07c64f4500f19b54ce29a7e3225c6245aaa758252253e7a1554b7801ff237833b31fd1d

test:
  secret_key_base: c49fb18a0da0631314b72ab98d529f7e1c6b7470a640e3ef6a5ecf73612c270414d27c9ccbc11f5ddfe3c3e23cf573f3369734d6b81bb22d66a7df22a01162f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
